services:
  - type: web
    name: rural-girls-platform
    env: node
    nodeVersion: 18.17.0
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true 